### ISSUE TITLE
Default limit doesn't work

### ISSUE THREAD

**Issue by marcinb** [DominikZabron/crypto-price-list#1]
Accessing `http://localhost` without the `limit` parameter gives me an error even though `DEFAULT_LIMIT` should apply?

```
web-api_1  | ERROR:root:'limit'
web-api_1  | Traceback (most recent call last):
web-api_1  |   File "./api/api.py", line 20, in do_GET
web-api_1  |     data = db.get_ranked_prices(int(qs['limit'][0]) or DEFAULT_LIMIT)
web-api_1  | KeyError: 'limit'
web-api_1  | 172.19.0.1 - - [20/Feb/2019 11:24:13] "GET / HTTP/1.1" 500 -
web-api_1  | ERROR:root:'limit'
web-api_1  | Traceback (most recent call last):
web-api_1  |   File "./api/api.py", line 20, in do_GET
web-api_1  |     data = db.get_ranked_prices(int(qs['limit'][0]) or DEFAULT_LIMIT)
web-api_1  | KeyError: 'limit'
```

**Comment by DominikZabron** [comment]
Fixed
